server:
  port: 9090

spring:
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.hulu.uls.common.pojo

---
spring:
  profiles: local
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

---
spring:
  profiles: dev
  datasource:
    username: root
    password: A!d!Me7TtK
    url: jdbc:mysql://121.36.69.7:3306/urban_legend?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: TvqS5yZ41F
    host: 121.36.69.7
    port: 6379
  data:
    mongodb:
      uri: mongodb://admin:ca1SanyDfY@121.36.69.7:27017/cms?authSource=admin
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

